spring.application.name=springdatajpademo2
# h2 database custom connection
spring.datasource.h2.url=jdbc:h2:mem:testdb
spring.datasource.h2.username=root
spring.datasource.h2.password=root
#you can get driver class name by search for Driver Class as we have added mysql-connector-j in pom
spring.datasource.h2.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
