spring.application.name=HibernateProblemDemo

#Postgres DB Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/Studentdb
spring.datasource.username=postgres
spring.datasource.password=postgres

#postgres driver/dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate table creation/update
spring.jpa.hibernate.ddl-auto=update

#show sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#sql logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE